defaults:
  - model: udm
  - backbone: resnet50

train:
  device: "cuda:1"
  batch_size: 64
  clean_ratio: 1
  nepoch: 2000
  num_workers: 8
  logdir: "/scratch/checkpoints/treedensity/"
  imsize: 64
  val_freq: 10

dataset:
  nbands: 4
